cirium_otp = {
    "file_path": "./dbt_code_generator/checklist/SourceFileAnalysis-cirium_-_Bronze.xlsx",
    "master_metadata_system": "cirium",
    "master_metadata_system_path": "flightstats",
    "data_set_name": "otp",
    "model_type" : "incremental",
    "tables": "flightstats_otp",
    "strategy" : "silver_incremental",
    "table_time_zone": "America/Chicago",
    "timestamp_format": "yyyy-MM-dd HH:mm:ss",
    "date_only_format": "yyyy-MM-dd",
    "first_data_row": "3",
    "output_file_name": "./dbt_code_generator/metadata/cirium_otp.json",
    "pos_ix": 3,
    "bronze_data_type_ix": 6,
    "bronze_to_silver_mapping_ix": 9,
    "column_name_ix": 11,
    "unique_key_ix": 13,
    "soft_delete_key_ix": 14,
    "duplicate_ranking_ix": 15,
    "is_nullable_ix": 16,
    "silver_data_type_ix": 17,
    "name_updated_at" : "originalsdt",
    "silver_partition_field" : "originalsdt",
    "storageLevel" : "MEMORY_ONLY_SER_2",
    "silver_partition_start" : 2018,
    "invalidate_hard_deletes" : False # this is the field for defining if it support soft delete
}