dmz = {
    "file_path": "./dbt_code_generator/checklist/SourceFileAnalysis-dmz.xlsx",
    "master_metadata_system": "dmz",
    "master_metadata_system_path": "dmz",
    "model_type" : "snapshot",
    "strategy" : "timestamp_with_late_arriving",
    "table_time_zone": "America/Chicago",
    "timestamp_format": "MMM-dd-yyyy HH:mm:ss",
    "date_only_format": "yyyy/MM/dd",
    "first_data_row": "0",
    "output_file_name": "C:\\Work\\Repos\\edp-x-light\\dbt_code_generator\\metadata\\dmz.json",
    "pos_ix": 3,
    "bronze_to_silver_mapping_ix": 9,
    "column_name_ix": 2,
    "unique_key_ix": 9,
    "soft_delete_key_ix": 0,
    "is_nullable_ix": 12,
    "source_data_type_ix": 4,
    "parquet_data_type_ix": 6,
    "bronze_data_type_ix": 6,
    "silver_data_type_ix": 0,
    "tabs_to_ignore": ["ASSUMPTIONS", "Checklist"]
}